var = input('Digite qualquer coisa ')
classe = type(var)
espaco = (var.isspace())
num= (var.isnumeric())
print(f'O tipo primitivo do valor é {classe}')
print('Só tem espaços? {} '.format(espaco)) 
print('É um número {} '.format(num))
print('É alfabético? ', var.isalpha())
print('É alfanúmerico? ', var.isalnum())
print('Está em maiuscula? ', var.isupper())
print('Está em minuscula? ', var.islower())
print('Está capitalizado? ', var.istitle())
